### ISSUE TITLE
pareto前沿面的那张图DTLZ

### ISSUE THREAD

**Issue by silkyrose** [425776024/MOEAD#1]
pareto前沿面的那张图DTLZ1无法画出
Test_fun = ZDT4
name = 'ZDT4'
替换成DTLZ1也无法画出pareto前沿面，代码无法执行

**Comment by silkyrose** [comment]
pareto前沿面的那张图DTLZ1无法画出
    Test_fun = ZDT4
    name = 'ZDT4'
替换成DTLZ1也无法画出pareto前沿面，代码无法执行

**Comment by silkyrose** [comment]
请问博主，这份代码究竟是DE还是GA呀？

**Comment by 425776024** [comment]
这份代码究竟是DE还是GA呀？DE和GA差不多吧。
代码无法执行是指？

**Comment by 425776024** [comment]
DTLZ1这些3目标函数的我注视掉了，执行效果不好

**Comment by silkyrose** [comment]
谢谢大神。
不太理解，目标2要这样处理一下，什么原因。另外，g函数是按什么原则生成的呀

    f2 = gx * (1 - np.sqrt(x / gx))

def g(X):
    g = 1 + 9 * (np.sum(X[0:], axis=0) / (X.shape[0] - 1))
    return g

**Comment by silkyrose** [comment]
好的，谢谢O(∩_∩)O
